service: node-simple-http-endpoint # NOTE: Don't put the word "google" in here

provider:
  name: google
  runtime: nodejs
  project: matchakon-api
  credentials: ${env:GOOGLE_APPLICATION_CREDENTIALS_PATH}.json 

plugins:
  - serverless-google-cloudfunctions
  - serverless-dotenv-plugin
custom:
  dotenv:
    include:
      - GOOGLE_APPLICATION_CREDENTIALS_PATH

package:
  exclude:
    - node_modules/**
    - .gitignore
    - .git/**

functions:
  matcha:
    handler: matcha
    events:
      - http:
          path: path